apiVersion: v1
kind: Service
metadata:
  name: my-kafka-ui-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: my-kafka-ui
    app.kubernetes.io/name: kafka-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
